name: CI

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: nightbarron/nodejs-simple-api:latest

            - name: Install ArgoCD CLI
              run: |
                curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
                chmod +x /usr/local/bin/argocd

            - name: Deploy to ArgoCD
              run: |
                argocd login argocd.k8s.vietnix.tech --insecure --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --grpc-web
                argocd app create nodejs-simple-api --repo https://github.com/nightbarron/nodejs-simple-api.git --path . --dest-server https://kubernetes.default.svc --dest-namespace vietnix-tech
                argocd app sync nodejs-simple-api